JUMP MACRO selector, offsetv
  DB 0eah
  DW offsestv
  DW selector
  ENDM

ECHOCH MACRO ascii
  mov ah, 2
  move dl, ascii
  int 21h
  endm

DESCRIPTOR STRUC
LIMITL DW 0
BASEL DW 0
BASEM DB 0
ATTRIBUTES DW 0
BASEH DB 0
DESCRIPTOR ENDS

PDESC STRUC
LIMIT DW 0
BASE DD 0
PDESC ENDS

ATDW = 92H
ATCE = 98H
.386P

DSEG SEGMENT USE16
GDT LABEL BYTE
DUMMY DESCRIPTOR <>
CODE DESCRIPTOR <0FFFFH,,,ATCE,>
CODE_SEL = CODE - GDT
DATAS DESCRIPTOR <0FFFFH,0H,11H,ATDW,0>
DATAS_SEL = DATAS - GDT
DATAD DESCRIPTOR<0FFFFH,,,ATDW,>
DATAD_SEL = DATAD - GDT
GDTLEN = $ - GDT
VGDTR PDESC <GDTLEN-1>
BUFFERLEN = 256
BUFFER DB BUFFERLEN DUP(0)
DSEG ENDS

CSEG SEGMENT USE16
  ASSUME CS:CSEG, DS:DSEG
START:
  mov ax, dseg
CSEG ENDS
  END START

