######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 13 16:02:43 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += w.h
SOURCES += main.cpp w.cpp
